const c=document.querySelector('#c'),x=c.getContext('2d'); let W,H,t=0,px=0,py=0,dir={x:0,y:0},inv=false,flash=false,toast='';
function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;W=c.width;H=c.height;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)} addEventListener('resize',resize);resize();
let items=['Vattenflaska','Konservburk','Ficklampa','AA-batterier','Bandage','Tändstickor','Hammare','Rep','Choklad','Regnjacka'];let bag=JSON.parse(localStorage.tdqBag||'[]');
function iso(X,Y){return [innerWidth/2+(X-Y)*42,innerHeight/2+(X+Y)*21]}
function rectIso(X,Y,w,d,col){let a=iso(X-px,Y-py),b=iso(X+w-px,Y-py),cc=iso(X+w-px,Y+d-py),e=iso(X-px,Y+d-py);x.fillStyle=col;x.beginPath();x.moveTo(...a);x.lineTo(...b);x.lineTo(...cc);x.lineTo(...e);x.fill()}
function building(X,Y,w,d,col){rectIso(X,Y,w,d,col); let a=iso(X-px,Y-py),b=iso(X+w-px,Y-py),cc=iso(X+w-px,Y+d-py),e=iso(X-px,Y+d-py);x.fillStyle='#351c18';x.beginPath();x.moveTo(a[0],a[1]);x.lineTo(b[0],b[1]);x.lineTo(b[0],b[1]-85);x.lineTo(a[0],a[1]-85);x.fill();x.fillStyle='#48241d';x.beginPath();x.moveTo(b[0],b[1]);x.lineTo(cc[0],cc[1]);x.lineTo(cc[0],cc[1]-85);x.lineTo(b[0],b[1]-85);x.fill();x.strokeStyle='#101614';x.lineWidth=3;x.strokeRect(a[0]+35,a[1]-64,26,38)}
function world(){x.fillStyle='#102b1c';x.fillRect(0,0,innerWidth,innerHeight); for(let i=-12;i<12;i++)rectIso(-18,i*1.2,36,.9,'#242b29'); rectIso(-5,-12,1.1,24,'#272d2b'); building(-10,-8,6,5,'#55554b');building(4,-8,7,5,'#55554b');building(-9,7,6,5,'#514c3e');building(5,7,7,5,'#514c3e');
 for(let i=0;i<18;i++){let q=iso((i*7%25)-12-px,(i*11%23)-11-py);x.fillStyle='#214b29';x.fillRect(q[0]-8,q[1]-35,16,24);x.fillStyle='#53351f';x.fillRect(q[0]-2,q[1]-11,4,18)}
 let p=iso(0,0);x.fillStyle='#111';x.fillRect(p[0]-11,p[1]+18,22,5);x.fillStyle='#315b50';x.fillRect(p[0]-10,p[1]-31,20,30);x.fillStyle='#ba946d';x.fillRect(p[0]-7,p[1]-47,14,15);x.fillStyle='#28221d';x.fillRect(p[0]-8,p[1]-50,16,5);
 x.strokeStyle='#8aa4a777';x.lineWidth=1;for(let i=0;i<80;i++){let rx=(i*83+t*130)%innerWidth,ry=(i*47+t*220)%innerHeight;x.beginPath();x.moveTo(rx,ry);x.lineTo(rx-5,ry+13);x.stroke()}
 if(flash){let g=x.createRadialGradient(p[0]+50,p[1],10,p[0]+50,p[1],150);g.addColorStop(0,'#ffe7a055');g.addColorStop(1,'#ffe7a000');x.fillStyle=g;x.fillRect(p[0]-20,p[1]-170,300,300)} }
function hud(){x.fillStyle='#06100ddd';x.fillRect(12,12,190,105);x.fillStyle='#ddd';x.font='15px monospace';x.fillText('THE DARK QUIET',24,34);x.fillText('HUNGER  ██████░░',24,59);x.fillText('TÖRST   █████░░░',24,80);x.fillText('7°C  REGN',24,103);if(toast){x.fillStyle='#06100ddd';x.fillRect(innerWidth/2-130,innerHeight-100,260,35);x.fillStyle='#e6c36d';x.fillText(toast,innerWidth/2-115,innerHeight-77)}if(inv){x.fillStyle='#07100cf2';x.fillRect(innerWidth*.18,innerHeight*.12,innerWidth*.64,innerHeight*.7);x.fillStyle='#fff';x.font='22px monospace';x.fillText('RYGGSÄCK',innerWidth*.21,innerHeight*.18);x.font='15px monospace';bag.forEach((a,i)=>x.fillText('▣ '+a,innerWidth*.22,innerHeight*.24+i*25));}}
function loop(ms){let nt=ms/1000,dt=Math.min(.03,nt-t||0);t=nt;if(!inv){px+=dir.x*dt*2.7;py+=dir.y*dt*2.7}world();hud();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const joy=document.querySelector('#joy'),nub=document.querySelector('#nub');function move(e){let r=joy.getBoundingClientRect(),q=e.touches?e.touches[0]:e,dx=q.clientX-(r.left+65),dy=q.clientY-(r.top+65),m=Math.hypot(dx,dy)||1,lim=Math.min(42,m),nx=dx/m,ny=dy/m;nub.style.transform=`translate(${nx*lim}px,${ny*lim}px)`;dir={x:(nx+ny)*.72,y:(ny-nx)*.72}}joy.addEventListener('touchstart',move);joy.addEventListener('touchmove',e=>{e.preventDefault();move(e)});joy.addEventListener('touchend',()=>{dir={x:0,y:0};nub.style.transform=''})
function say(s){toast=s;setTimeout(()=>toast='',1500)}document.querySelector('#inv').onclick=()=>inv=!inv;document.querySelector('#flash').onclick=()=>{flash=!flash;say(flash?'Ficklampa på':'Ficklampa av')};document.querySelector('#build').onclick=()=>say('BYGGMENY – mobiltest');document.querySelector('#act').onclick=()=>{let a=items[Math.floor(Math.random()*items.length)];bag.push(a);localStorage.tdqBag=JSON.stringify(bag);say('Hittade: '+a)};